package com.softcorp.sigtec.core.theme

import androidx.compose.ui.graphics.Color

// ===== Modo claro =====
// Los marcados con (doc) vienen de la sección 12.1 del documento; el resto se derivó de la semilla #00677E.
internal val PrimarioClaro = Color(0xFF00677E)               // (doc)
internal val SobrePrimarioClaro = Color(0xFFFFFFFF)          // (doc)
internal val ContenedorPrimarioClaro = Color(0xFFB3EBFF)     // (doc)
internal val SobreContenedorPrimarioClaro = Color(0xFF001F28) // (doc)
internal val SecundarioClaro = Color(0xFF4B6269)             // (doc)
internal val SobreSecundarioClaro = Color(0xFFFFFFFF)
internal val ContenedorSecundarioClaro = Color(0xFFCEE7EF)   // (doc)
internal val SobreContenedorSecundarioClaro = Color(0xFF061F25)
internal val TerciarioClaro = Color(0xFF565D7E)              // (doc)
internal val SobreTerciarioClaro = Color(0xFFFFFFFF)
internal val ContenedorTerciarioClaro = Color(0xFFDDE1FF)
internal val SobreContenedorTerciarioClaro = Color(0xFF121A37)
internal val ErrorClaro = Color(0xFFBA1A1A)                  // (doc)
internal val SobreErrorClaro = Color(0xFFFFFFFF)
internal val ContenedorErrorClaro = Color(0xFFFFDAD6)        // (doc)
internal val SobreContenedorErrorClaro = Color(0xFF410002)
internal val SuperficieClaro = Color(0xFFFBFCFE)             // (doc)
internal val SobreSuperficieClaro = Color(0xFF191C1D)        // (doc)
internal val VarianteSuperficieClaro = Color(0xFFDBE4E8)
internal val SobreVarianteSuperficieClaro = Color(0xFF40484C)
internal val ContornoClaro = Color(0xFF70787C)               // (doc)
internal val VarianteContornoClaro = Color(0xFFBFC8CC)
internal val SuperficieInversaClaro = Color(0xFF2E3132)
internal val SobreSuperficieInversaClaro = Color(0xFFEFF1F2)
internal val PrimarioInversoClaro = Color(0xFF5DD5FC)
internal val ContenedorMasBajoClaro = Color(0xFFFFFFFF)
internal val ContenedorBajoClaro = Color(0xFFF2F5F7)
internal val ContenedorClaro = Color(0xFFECF1F3)
internal val ContenedorAltoClaro = Color(0xFFE6EBED)
internal val ContenedorMasAltoClaro = Color(0xFFE0E5E7)

// ===== Modo oscuro (mismos tonos de la semilla, invertidos según Material 3) =====
internal val PrimarioOscuro = Color(0xFF5DD5FC)
internal val SobrePrimarioOscuro = Color(0xFF003544)
internal val ContenedorPrimarioOscuro = Color(0xFF004E5F)
internal val SobreContenedorPrimarioOscuro = Color(0xFFB3EBFF)
internal val SecundarioOscuro = Color(0xFFB2CBD3)
internal val SobreSecundarioOscuro = Color(0xFF1D343A)
internal val ContenedorSecundarioOscuro = Color(0xFF344A51)
internal val SobreContenedorSecundarioOscuro = Color(0xFFCEE7EF)
internal val TerciarioOscuro = Color(0xFFBFC4EB)
internal val SobreTerciarioOscuro = Color(0xFF282F4D)
internal val ContenedorTerciarioOscuro = Color(0xFF3F4565)
internal val SobreContenedorTerciarioOscuro = Color(0xFFDDE1FF)
internal val ErrorOscuro = Color(0xFFFFB4AB)
internal val SobreErrorOscuro = Color(0xFF690005)
internal val ContenedorErrorOscuro = Color(0xFF93000A)
internal val SobreContenedorErrorOscuro = Color(0xFFFFDAD6)
internal val SuperficieOscuro = Color(0xFF101415)
internal val SobreSuperficieOscuro = Color(0xFFE1E3E4)
internal val VarianteSuperficieOscuro = Color(0xFF40484C)
internal val SobreVarianteSuperficieOscuro = Color(0xFFBFC8CC)
internal val ContornoOscuro = Color(0xFF8A9296)
internal val VarianteContornoOscuro = Color(0xFF40484C)
internal val SuperficieInversaOscuro = Color(0xFFE1E3E4)
internal val SobreSuperficieInversaOscuro = Color(0xFF2E3132)
internal val PrimarioInversoOscuro = Color(0xFF00677E)
internal val ContenedorMasBajoOscuro = Color(0xFF0B0F10)
internal val ContenedorBajoOscuro = Color(0xFF191C1D)
internal val ContenedorOscuro = Color(0xFF1D2021)
internal val ContenedorAltoOscuro = Color(0xFF272A2C)
internal val ContenedorMasAltoOscuro = Color(0xFF323537)